// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GenOptions controls generation.
 */
export class GenOptions {
    /**
     * Creates a new GenOptions instance.
     * @param {Partial<GenOptions>} [$$source = {}] - The source object to create the GenOptions.
     */
    constructor($$source = {}) {
        if (!("maxNewTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxNewTokens"] = 0;
        }
        if (!("temperature" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["temperature"] = 0;
        }
        if (!("topK" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["topK"] = 0;
        }
        if (!("topP" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["topP"] = 0;
        }
        if (!("repetitionPenalty" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repetitionPenalty"] = 0;
        }
        if (!("systemPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemPrompt"] = "";
        }
        if (!("useChatTemplate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useChatTemplate"] = false;
        }
        if (!("seed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seed"] = 0;
        }
        if (!("stream" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["stream"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GenOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenOptions(/** @type {Partial<GenOptions>} */($$parsedSource));
    }
}
