// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AsrService runs speech recognition. Backend "sensevoice" uses FunASR
 * SenseVoiceSmall (ONNX, in-process); "whisper" shells out to whisper.cpp
 * (Metal on Apple Silicon).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadModel fetches the default ggml-base.bin model via the configured
 * proxy, reporting progress through the "dl:progress" event.
 * @returns {$CancellablePromise<void>}
 */
export function DownloadModel() {
    return $Call.ByID(3741332444);
}

/**
 * IsRecording reports whether a recording is in progress.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRecording() {
    return $Call.ByID(2695005706);
}

/**
 * SetBackend switches between "sensevoice" and "whisper".
 * @param {string} backend
 * @returns {$CancellablePromise<void>}
 */
export function SetBackend(backend) {
    return $Call.ByID(1791142931, backend);
}

/**
 * SetBin changes the whisper-cli path and saves the config.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetBin(path) {
    return $Call.ByID(3375788898, path);
}

/**
 * SetModel changes the whisper model path and saves the config.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetModel(path) {
    return $Call.ByID(3315853774, path);
}

/**
 * SetSenseVoiceDir sets the FunASR model directory and loads it.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetSenseVoiceDir(dir) {
    return $Call.ByID(1811084304, dir);
}

/**
 * StartRecording begins microphone capture via ffmpeg (AVFoundation on
 * macOS). The recording is written to a temp WAV (16k mono).
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording() {
    return $Call.ByID(1698474832);
}

/**
 * Status reports the ASR backend readiness and busy state.
 * @returns {$CancellablePromise<$models.AsrStatus>}
 */
export function Status() {
    return $Call.ByID(2192543133).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StopAndTranscribe stops the recording and transcribes it with the active
 * backend.
 * @param {string} language
 * @returns {$CancellablePromise<string>}
 */
export function StopAndTranscribe(language) {
    return $Call.ByID(2936323399, language);
}

/**
 * Transcribe runs whisper.cpp on an audio file and returns the transcript.
 * language is an ISO code (en/zh/...) or "auto".
 * @param {string} audioPath
 * @param {string} language
 * @returns {$CancellablePromise<string>}
 */
export function Transcribe(audioPath, language) {
    return $Call.ByID(970260876, audioPath, language);
}

/**
 * TranscribeBase64 accepts base64-encoded audio bytes and transcribes them
 * with the selected backend.
 * @param {string} dataB64
 * @param {string} language
 * @param {string} filename
 * @returns {$CancellablePromise<string>}
 */
export function TranscribeBase64(dataB64, language, filename) {
    return $Call.ByID(1734453899, dataB64, language, filename);
}

// Private type creation functions
const $$createType0 = $models.AsrStatus.createFrom;
