// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HFHubService exposes HuggingFace Hub and local model management to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hfhub$0 from "./internal/hfhub/models.js";

/**
 * DeleteModel removes a local model directory.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModel(id) {
    return $Call.ByID(1261017156, id);
}

/**
 * DownloadModel downloads a set of files from a repository into the local
 * model root (ModelRoot/<repoID>/...). When files is empty every file in the
 * repository is downloaded. Progress events are emitted as "dl:progress".
 * @param {string} repoID
 * @param {string[]} files
 * @param {string} revision
 * @returns {$CancellablePromise<string>}
 */
export function DownloadModel(repoID, files, revision) {
    return $Call.ByID(1773042017, repoID, files, revision);
}

/**
 * LocalModels lists the models stored under the model root.
 * @returns {$CancellablePromise<hfhub$0.LocalModel[]>}
 */
export function LocalModels() {
    return $Call.ByID(3137523013).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ModelFiles lists the file tree of a remote repository.
 * @param {string} repo
 * @param {string} revision
 * @param {string} subPath
 * @returns {$CancellablePromise<hfhub$0.FileInfo[]>}
 */
export function ModelFiles(repo, revision, subPath) {
    return $Call.ByID(1272193252, repo, revision, subPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ModelInfo fetches metadata for a repository.
 * @param {string} repo
 * @returns {$CancellablePromise<hfhub$0.Model | null>}
 */
export function ModelInfo(repo) {
    return $Call.ByID(3751250913, repo).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ModelRoot returns the local model root.
 * @returns {$CancellablePromise<string>}
 */
export function ModelRoot() {
    return $Call.ByID(1999226241);
}

/**
 * OpenModel opens a local model directory in the file manager.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenModel(id) {
    return $Call.ByID(657761145, id);
}

/**
 * SearchModel finds models on the Hub.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<hfhub$0.Model[]>}
 */
export function SearchModel(query, limit) {
    return $Call.ByID(3371243037, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SetModelRoot changes the local model root and saves the config.
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function SetModelRoot(dir) {
    return $Call.ByID(2051345305, dir);
}

// Private type creation functions
const $$createType0 = hfhub$0.LocalModel.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = hfhub$0.FileInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = hfhub$0.Model.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
