// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LlmService manages ONNX small-model inference (Qwen / MiniCPM families).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "./internal/llm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultModelDir returns the configured LLM model directory.
 * @returns {$CancellablePromise<string>}
 */
export function DefaultModelDir() {
    return $Call.ByID(3218165519);
}

/**
 * Generate produces a completion, streaming tokens via the "llm:token" event
 * when opts.Stream is true. Reasoning sections (if the model emits them) are
 * streamed via the "llm:reasoning" event. Returns the full generated text.
 * @param {string} prompt
 * @param {llm$0.GenOptions} opts
 * @returns {$CancellablePromise<string>}
 */
export function Generate(prompt, opts) {
    return $Call.ByID(2623413705, prompt, opts);
}

/**
 * Load loads an ONNX model directory (model.onnx + config.json +
 * tokenizer.json). The directory may also be a model ID under the model root.
 * @param {string} dirOrID
 * @returns {$CancellablePromise<void>}
 */
export function Load(dirOrID) {
    return $Call.ByID(1632724950, dirOrID);
}

/**
 * LocalOnnxModels returns local model directories that look like LLM ONNX
 * exports (model.onnx + config.json).
 * @returns {$CancellablePromise<string[]>}
 */
export function LocalOnnxModels() {
    return $Call.ByID(116515400).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Status returns the current LLM engine state.
 * @returns {$CancellablePromise<$models.LlmStatus>}
 */
export function Status() {
    return $Call.ByID(2320029144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Stop aborts the current generation.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1452420030);
}

/**
 * Unload releases the loaded model.
 * @returns {$CancellablePromise<void>}
 */
export function Unload() {
    return $Call.ByID(687908825);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.LlmStatus.createFrom;
