// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AsrStatus describes the whisper.cpp setup.
 */
export class AsrStatus {
    /**
     * Creates a new AsrStatus instance.
     * @param {Partial<AsrStatus>} [$$source = {}] - The source object to create the AsrStatus.
     */
    constructor($$source = {}) {
        if (!("binReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binReady"] = false;
        }
        if (!("modelReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["modelReady"] = false;
        }
        if (!("binPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binPath"] = "";
        }
        if (!("modelPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelPath"] = "";
        }
        if (!("senseVoiceDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["senseVoiceDir"] = "";
        }
        if (!("senseVoiceReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["senseVoiceReady"] = false;
        }
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }
        if (!("transcribing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["transcribing"] = false;
        }
        if (!("recording" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recording"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AsrStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AsrStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AsrStatus(/** @type {Partial<AsrStatus>} */($$parsedSource));
    }
}

/**
 * LlmStatus describes the current LLM engine state.
 */
export class LlmStatus {
    /**
     * Creates a new LlmStatus instance.
     * @param {Partial<LlmStatus>} [$$source = {}] - The source object to create the LlmStatus.
     */
    constructor($$source = {}) {
        if (!("loaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loaded"] = false;
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (!("modelType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelType"] = "";
        }
        if (!("generating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["generating"] = false;
        }
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }
        if (!("vision" in $$source)) {
            /**
             * Vision reports whether the loaded model can understand images directly
             * (has a vision encoder / image token config).
             * @member
             * @type {boolean}
             */
            this["vision"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LlmStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LlmStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LlmStatus(/** @type {Partial<LlmStatus>} */($$parsedSource));
    }
}

/**
 * OcrStatus describes the current OCR engine configuration.
 */
export class OcrStatus {
    /**
     * Creates a new OcrStatus instance.
     * @param {Partial<OcrStatus>} [$$source = {}] - The source object to create the OcrStatus.
     */
    constructor($$source = {}) {
        if (!("loaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loaded"] = false;
        }
        if (!("detPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detPath"] = "";
        }
        if (!("recPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["recPath"] = "";
        }
        if (!("clsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clsPath"] = "";
        }
        if (!("dictPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dictPath"] = "";
        }
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OcrStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OcrStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OcrStatus(/** @type {Partial<OcrStatus>} */($$parsedSource));
    }
}
