// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OcrService manages PaddleOCR ONNX models and runs recognition.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as paddleocr$0 from "./internal/paddleocr/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultModelDir returns where default OCR models are stored.
 * @returns {$CancellablePromise<string>}
 */
export function DefaultModelDir() {
    return $Call.ByID(2031802370);
}

/**
 * DefaultPaths returns the expected default OCR model paths for a language and
 * tier.
 * @param {string} lang
 * @param {string} tier
 * @returns {$CancellablePromise<[string, string, string, string, string]>}
 */
export function DefaultPaths(lang, tier) {
    return $Call.ByID(2143973546, lang, tier);
}

/**
 * GuessPathsFromDir attempts to locate det/rec/cls/ori/dict files inside a
 * directory by filename heuristics.
 * @param {string} dir
 * @returns {$CancellablePromise<[string, string, string, string, string]>}
 */
export function GuessPathsFromDir(dir) {
    return $Call.ByID(2423245937, dir);
}

/**
 * InstallDefaults downloads a set of PaddleOCR ONNX models. lang only selects
 * a sub-folder name; tier is "tiny"/"small"/"medium" (PP-OCRv6 model tiers).
 * @param {string} lang
 * @param {string} tier
 * @returns {$CancellablePromise<void>}
 */
export function InstallDefaults(lang, tier) {
    return $Call.ByID(3216677890, lang, tier);
}

/**
 * Load opens the given ONNX model files. oriPath (document orientation
 * classifier, optional) corrects rotated scans before recognition.
 * @param {string} detPath
 * @param {string} recPath
 * @param {string} clsPath
 * @param {string} oriPath
 * @param {string} dictPath
 * @returns {$CancellablePromise<void>}
 */
export function Load(detPath, recPath, clsPath, oriPath, dictPath) {
    return $Call.ByID(889502433, detPath, recPath, clsPath, oriPath, dictPath);
}

/**
 * OCRTierNames returns the available PP-OCRv6 tiers.
 * @returns {$CancellablePromise<string[]>}
 */
export function OCRTierNames() {
    return $Call.ByID(643899493).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OcrClipboard OCRs the image currently on the system clipboard.
 * @returns {$CancellablePromise<string>}
 */
export function OcrClipboard() {
    return $Call.ByID(1450231439);
}

/**
 * Recognise runs OCR on an image file.
 * @param {string} path
 * @returns {$CancellablePromise<paddleocr$0.Result | null>}
 */
export function Recognise(path) {
    return $Call.ByID(4235862494, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RecogniseBase64 runs OCR on base64-encoded image data.
 * @param {string} data
 * @returns {$CancellablePromise<paddleocr$0.Result | null>}
 */
export function RecogniseBase64(data) {
    return $Call.ByID(2105576417, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ScreenshotOcr interactively captures a screen region and OCRs it.
 * @returns {$CancellablePromise<string>}
 */
export function ScreenshotOcr() {
    return $Call.ByID(821445331);
}

/**
 * SetThreads configures the ONNX thread count.
 * @param {number} n
 * @returns {$CancellablePromise<void>}
 */
export function SetThreads(n) {
    return $Call.ByID(1429262896, n);
}

/**
 * Status returns the current OCR configuration.
 * @returns {$CancellablePromise<$models.OcrStatus>}
 */
export function Status() {
    return $Call.ByID(771308903).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = paddleocr$0.Result.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.OcrStatus.createFrom;
