// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuntimeService manages the ONNX Runtime shared library lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ort$0 from "./internal/ort/models.js";

/**
 * Config returns the current application configuration.
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function Config() {
    return $Call.ByID(3113978143).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Download fetches and extracts the ONNX Runtime shared library. Progress is
 * reported through the "dl:progress" event.
 * @param {string} version
 * @returns {$CancellablePromise<string>}
 */
export function Download(version) {
    return $Call.ByID(1709656929, version);
}

/**
 * EnsureRuntime initializes the ONNX Runtime environment, downloading the
 * library first if it is missing.
 * @returns {$CancellablePromise<string>}
 */
export function EnsureRuntime() {
    return $Call.ByID(3989383393);
}

/**
 * LibFileName returns the library file name for the host platform.
 * @returns {$CancellablePromise<string>}
 */
export function LibFileName() {
    return $Call.ByID(3859892313);
}

/**
 * OpenFolder opens the given directory in the file manager.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(path) {
    return $Call.ByID(132835697, path);
}

/**
 * OpenMain shows and focuses the main window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenMain() {
    return $Call.ByID(4156475636);
}

/**
 * SaveConfig persists the configuration and returns errors if any.
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig() {
    return $Call.ByID(3695685854);
}

/**
 * Status returns whether the ONNX Runtime library is present and loadable.
 * @returns {$CancellablePromise<ort$0.RuntimeStatus>}
 */
export function Status() {
    return $Call.ByID(3944379415).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * TestProxy verifies that a proxy can reach the HuggingFace Hub.
 * @param {string} proxy
 * @returns {$CancellablePromise<void>}
 */
export function TestProxy(proxy) {
    return $Call.ByID(1229885571, proxy);
}

/**
 * Version returns the bundled expected ONNX Runtime version.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(644606879);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ort$0.RuntimeStatus.createFrom;
