// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RuntimeStatus describes whether a runtime library is present locally.
 */
export class RuntimeStatus {
    /**
     * Creates a new RuntimeStatus instance.
     * @param {Partial<RuntimeStatus>} [$$source = {}] - The source object to create the RuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("present" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["present"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus(/** @type {Partial<RuntimeStatus>} */($$parsedSource));
    }
}
