// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds all user-adjustable paths for the application.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("modelRoot" in $$source)) {
            /**
             * ModelRoot is where downloaded HuggingFace models are stored.
             * @member
             * @type {string}
             */
            this["modelRoot"] = "";
        }
        if (!("onnxLibPath" in $$source)) {
            /**
             * OnnxLibPath is the location of the ONNX Runtime shared library.
             * @member
             * @type {string}
             */
            this["onnxLibPath"] = "";
        }
        if (!("ocrDir" in $$source)) {
            /**
             * OcrDir is where PaddleOCR ONNX models live.
             * @member
             * @type {string}
             */
            this["ocrDir"] = "";
        }
        if (!("llmDir" in $$source)) {
            /**
             * LlmDir is where ONNX LLM (MiniCPM) exports live.
             * @member
             * @type {string}
             */
            this["llmDir"] = "";
        }
        if (!("proxy" in $$source)) {
            /**
             * Proxy is an optional HTTP(S) proxy URL (e.g. "http://127.0.0.1:7890")
             * used for HuggingFace and GitHub downloads.
             * @member
             * @type {string}
             */
            this["proxy"] = "";
        }
        if (!("coreML" in $$source)) {
            /**
             * CoreML enables the ONNX Runtime CoreML execution provider on macOS to
             * accelerate CNN models (OCR) on the Apple GPU / Neural Engine.
             * @member
             * @type {boolean}
             */
            this["coreML"] = false;
        }
        if (!("whisperBin" in $$source)) {
            /**
             * WhisperBin is the path to the whisper.cpp CLI (Metal), used for speech
             * recognition.
             * @member
             * @type {string}
             */
            this["whisperBin"] = "";
        }
        if (!("whisperModel" in $$source)) {
            /**
             * WhisperModel is the path to a whisper.cpp GGML/GGUF model.
             * @member
             * @type {string}
             */
            this["whisperModel"] = "";
        }
        if (!("asrBackend" in $$source)) {
            /**
             * AsrBackend selects the ASR engine: "sensevoice" (FunASR SenseVoiceSmall,
             * ONNX) or "whisper" (whisper.cpp).
             * @member
             * @type {string}
             */
            this["asrBackend"] = "";
        }
        if (!("senseVoiceDir" in $$source)) {
            /**
             * SenseVoiceDir is the FunASR SenseVoiceSmall ONNX model directory.
             * @member
             * @type {string}
             */
            this["senseVoiceDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}
