// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileInfo is a single entry in a repository tree.
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{"size": number} | null | undefined}
             */
            this["lfs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * LocalModel describes a model directory found under the model root.
 */
export class LocalModel {
    /**
     * Creates a new LocalModel instance.
     * @param {Partial<LocalModel>} [$$source = {}] - The source object to create the LocalModel.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modified"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * llm, onnx, paddle, hf, other
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalModel}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField5_0($$parsedSource["files"]);
        }
        return new LocalModel(/** @type {Partial<LocalModel>} */($$parsedSource));
    }
}

/**
 * Model is a single model listed by the Hub API.
 */
export class Model {
    /**
     * Creates a new Model instance.
     * @param {Partial<Model>} [$$source = {}] - The source object to create the Model.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("downloads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloads"] = 0;
        }
        if (!("likes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["likes"] = 0;
        }
        if (!("pipeline_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pipeline_tag"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "";
        }
        if (!("siblings" in $$source)) {
            /**
             * @member
             * @type {{"rfilename": string}[]}
             */
            this["siblings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Model}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("siblings" in $$parsedSource) {
            $$parsedSource["siblings"] = $$createField6_0($$parsedSource["siblings"]);
        }
        return new Model(/** @type {Partial<Model>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
