// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Line is a recognized text line.
 */
export class Line {
    /**
     * Creates a new Line instance.
     * @param {Partial<Line>} [$$source = {}] - The source object to create the Line.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("confidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (!("box" in $$source)) {
            /**
             * box in the (possibly corrected) image pixels
             * @member
             * @type {number[][]}
             */
            this["box"] = Array.from({ length: 4 }, () => Array.from({ length: 2 }, () => 0));
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Line instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Line}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Line(/** @type {Partial<Line>} */($$parsedSource));
    }
}

/**
 * Result is the complete OCR output for one image.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {Line[]}
             */
            this["lines"] = [];
        }
        if (!("elapsedMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedMs"] = 0;
        }
        if (!("rotation" in $$source)) {
            /**
             * Rotation is the clockwise degrees applied to the input to correct its
             * document orientation (0/90/180/270). Boxes are in the corrected space.
             * @member
             * @type {number}
             */
            this["rotation"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField0_0($$parsedSource["lines"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Line.createFrom;
const $$createType1 = $Create.Array($$createType0);
